name: Build and deploy an updated version of the website

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout gbdev/pandocs
      uses: actions/checkout@v2
      with:
        repository: gbdev/pandocs
        path: folder/repo

    - name: Checkout gbdev/pandocs master
      uses: actions/checkout@v2
      with:
        repository: gbdev/pandocs
        ref: master
        path: folder/build

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r folder/repo/render/requirements.txt

    - name: Install pandoc
      uses: r-lib/actions/setup-pandoc@v1
      with:
        pandoc-version: '2.7.3'

    - name: Install XeLaTeX
      run: sudo apt-get install texlive-xetex

    - working-directory: folder/
      run: |
        cd repo/render
        ./merge.sh
        npx vuepress build
        pandoc index.md --pdf-engine=xelatex -o pandocs.pdf
        mkdir dist
        cp .vuepress/dist/* dist/ -r
        cp pandocs.pdf dist/
        cd ../..
        cp -a repo/render/dist/. build/
        cd build
        mkdir -m 700 ~/.ssh
        echo "${{ secrets.SSH_KEY_SECRET }}" > ~/.ssh/id_ed25519
        chmod 0600 ~/.ssh/id_ed25519
        git config --local user.name "GitHub Action"
        git config --global user.email "community@gbdev.io"
        git add .
        git commit -m "Update build" && git push || :
   
    - name: Upload PDF build
      uses: actions/upload-artifact@v1
      with:
        name: Pandocs PDF build
        path: folder/build/pandocs.pdf
