name: Build and deploy an updated version of the website

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout gbdev/pandocs
      uses: actions/checkout@v2
      with:
        repository: gbdev/pandocs
        path: folder/repo
    - name: Checkout gbdev/pandocs
      uses: actions/checkout@v2
      with:
        repository: gbdev/pandocs
        ref: master
        path: folder/build

    - uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r folder/repo/render/requirements.txt

    - working-directory: folder/
      run: |
        cd repo/render
        ./merge.sh
        npx vuepress build
        mkdir dist
        cp .vuepress/dist/* dist/ -r
        cd ..
        cp -a repo/dist/. build/
        cd build
        mkdir -m 700 ~/.ssh
        echo "${{ secrets.SSH_KEY_SECRET }}" > ~/.ssh/id_ed25519
        chmod 0600 ~/.ssh/id_ed25519
        git config --local user.name "GitHub Action"
        git config --global user.email "community@gbdev.io"
        git add .
        git commit -m "Update build" && git push || :